name: "build"
on:
  workflow_dispatch:
  push:
    tags:
        - "*"

jobs:
  relase:
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-musl
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            target_rustflags: ''
    
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: stable
      - name: Ref Type
        id: ref-type
        run: cargo run --package ref-type -- --reference ${{ github.ref }}
      
      - name: Package
        id: package
        env:
          TARGET: ${{ matrix.target }}
          REF: ${{ github.ref }}
          OS: ${{ matrix.os }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
        run: ./bin/package
        shell: bash
      
      - name: Publish Archive
        uses: softprops/action-gh-release@v0.1.5
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: false
          files: ${{ steps.package.outputs.archive }}
          prerelease: ${{ steps.ref-type.outputs.value != 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    